/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'cms-admins': CmsAdminAuthOperations;
  };
  blocks: {};
  collections: {
    'cms-admins': CmsAdmin;
    articles: Article;
    beliefs: Belief;
    templates: Template;
    'emotion-categories': EmotionCategory;
    'emotion-intensities': EmotionIntensity;
    'emotion-branches': EmotionBranch;
    'emotion-tools': EmotionTool;
    'mindfulness-scenarios': MindfulnessScenario;
    'mindfulness-habits': MindfulnessHabit;
    'life-events': LifeEvent;
    'belief-method-media': BeliefMethodMedia;
    'template-records': TemplateRecord;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'cms-admins': CmsAdminsSelect<false> | CmsAdminsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    beliefs: BeliefsSelect<false> | BeliefsSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    'emotion-categories': EmotionCategoriesSelect<false> | EmotionCategoriesSelect<true>;
    'emotion-intensities': EmotionIntensitiesSelect<false> | EmotionIntensitiesSelect<true>;
    'emotion-branches': EmotionBranchesSelect<false> | EmotionBranchesSelect<true>;
    'emotion-tools': EmotionToolsSelect<false> | EmotionToolsSelect<true>;
    'mindfulness-scenarios': MindfulnessScenariosSelect<false> | MindfulnessScenariosSelect<true>;
    'mindfulness-habits': MindfulnessHabitsSelect<false> | MindfulnessHabitsSelect<true>;
    'life-events': LifeEventsSelect<false> | LifeEventsSelect<true>;
    'belief-method-media': BeliefMethodMediaSelect<false> | BeliefMethodMediaSelect<true>;
    'template-records': TemplateRecordsSelect<false> | TemplateRecordsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: CmsAdmin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsAdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-admins".
 */
export interface CmsAdmin {
  id: number;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms-admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  legacyId?: string | null;
  title: string;
  slug: string;
  subtitle?: string | null;
  coverImage: string;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  contentText: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beliefs".
 */
export interface Belief {
  id: number;
  legacyId: string;
  order: number;
  oldBelief: string;
  newBelief: string;
  color: string;
  bgColor: string;
  theory: {
    item: string;
    id?: string | null;
  }[];
  methods:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dailyApplication: {
    item: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  legacyId: string;
  title: string;
  description: string;
  icon: string;
  color: string;
  bgColor: string;
  questionCount: number;
  scenarios?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  layers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emotion-categories".
 */
export interface EmotionCategory {
  id: number;
  legacyId: string;
  name: string;
  icon: string;
  color: string;
  bgColor: string;
  emotions:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emotion-intensities".
 */
export interface EmotionIntensity {
  id: number;
  legacyId: string;
  emotion: string;
  mild: string;
  moderate: string;
  severe: string;
  color: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emotion-branches".
 */
export interface EmotionBranch {
  id: number;
  legacyId: string;
  name: string;
  icon: string;
  color: string;
  bgColor: string;
  description: string;
  leaves:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  recommendedTools: {
    item: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emotion-tools".
 */
export interface EmotionTool {
  id: number;
  legacyId: string;
  name: string;
  icon: string;
  duration: string;
  description: string;
  forEmotions: {
    item: string;
    id?: string | null;
  }[];
  color: string;
  type: 'breathing' | 'meditation' | 'worksheet' | 'dialogue' | 'exercise';
  steps?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mindfulness-scenarios".
 */
export interface MindfulnessScenario {
  id: number;
  legacyId: string;
  title: string;
  icon: string;
  color: string;
  situation: string;
  cycle: string;
  steps:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  questions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mindfulness-habits".
 */
export interface MindfulnessHabit {
  id: number;
  legacyId: string;
  title: string;
  description: string;
  examples?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "life-events".
 */
export interface LifeEvent {
  id: number;
  legacyId: string;
  date: string;
  title: string;
  description: string;
  type: 'positive' | 'negative';
  images?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "belief-method-media".
 */
export interface BeliefMethodMedia {
  id: number;
  methodId: string;
  type: 'image' | 'video' | 'audio';
  url: string;
  caption?: string | null;
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "template-records".
 */
export interface TemplateRecord {
  id: number;
  templateId: string;
  templateTitle: string;
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cms-admins';
        value: number | CmsAdmin;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'beliefs';
        value: number | Belief;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'emotion-categories';
        value: number | EmotionCategory;
      } | null)
    | ({
        relationTo: 'emotion-intensities';
        value: number | EmotionIntensity;
      } | null)
    | ({
        relationTo: 'emotion-branches';
        value: number | EmotionBranch;
      } | null)
    | ({
        relationTo: 'emotion-tools';
        value: number | EmotionTool;
      } | null)
    | ({
        relationTo: 'mindfulness-scenarios';
        value: number | MindfulnessScenario;
      } | null)
    | ({
        relationTo: 'mindfulness-habits';
        value: number | MindfulnessHabit;
      } | null)
    | ({
        relationTo: 'life-events';
        value: number | LifeEvent;
      } | null)
    | ({
        relationTo: 'belief-method-media';
        value: number | BeliefMethodMedia;
      } | null)
    | ({
        relationTo: 'template-records';
        value: number | TemplateRecord;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms-admins';
    value: number | CmsAdmin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms-admins';
    value: number | CmsAdmin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-admins_select".
 */
export interface CmsAdminsSelect<T extends boolean = true> {
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  legacyId?: T;
  title?: T;
  slug?: T;
  subtitle?: T;
  coverImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  contentText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "beliefs_select".
 */
export interface BeliefsSelect<T extends boolean = true> {
  legacyId?: T;
  order?: T;
  oldBelief?: T;
  newBelief?: T;
  color?: T;
  bgColor?: T;
  theory?:
    | T
    | {
        item?: T;
        id?: T;
      };
  methods?: T;
  dailyApplication?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  legacyId?: T;
  title?: T;
  description?: T;
  icon?: T;
  color?: T;
  bgColor?: T;
  questionCount?: T;
  scenarios?:
    | T
    | {
        item?: T;
        id?: T;
      };
  layers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emotion-categories_select".
 */
export interface EmotionCategoriesSelect<T extends boolean = true> {
  legacyId?: T;
  name?: T;
  icon?: T;
  color?: T;
  bgColor?: T;
  emotions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emotion-intensities_select".
 */
export interface EmotionIntensitiesSelect<T extends boolean = true> {
  legacyId?: T;
  emotion?: T;
  mild?: T;
  moderate?: T;
  severe?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emotion-branches_select".
 */
export interface EmotionBranchesSelect<T extends boolean = true> {
  legacyId?: T;
  name?: T;
  icon?: T;
  color?: T;
  bgColor?: T;
  description?: T;
  leaves?: T;
  recommendedTools?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emotion-tools_select".
 */
export interface EmotionToolsSelect<T extends boolean = true> {
  legacyId?: T;
  name?: T;
  icon?: T;
  duration?: T;
  description?: T;
  forEmotions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  color?: T;
  type?: T;
  steps?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mindfulness-scenarios_select".
 */
export interface MindfulnessScenariosSelect<T extends boolean = true> {
  legacyId?: T;
  title?: T;
  icon?: T;
  color?: T;
  situation?: T;
  cycle?: T;
  steps?: T;
  questions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mindfulness-habits_select".
 */
export interface MindfulnessHabitsSelect<T extends boolean = true> {
  legacyId?: T;
  title?: T;
  description?: T;
  examples?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "life-events_select".
 */
export interface LifeEventsSelect<T extends boolean = true> {
  legacyId?: T;
  date?: T;
  title?: T;
  description?: T;
  type?: T;
  images?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "belief-method-media_select".
 */
export interface BeliefMethodMediaSelect<T extends boolean = true> {
  methodId?: T;
  type?: T;
  url?: T;
  caption?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "template-records_select".
 */
export interface TemplateRecordsSelect<T extends boolean = true> {
  templateId?: T;
  templateTitle?: T;
  answers?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}