/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    'cms-admins': CmsAdminAuthOperations;
  };
  blocks: {};
  collections: {
    'cms-admins': CmsAdmin;
    'app-users': AppUser;
    babies: Baby;
    'baby-users': BabyUser;
    activities: Activity;
    'daily-stats': DailyStat;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'cms-admins': CmsAdminsSelect<false> | CmsAdminsSelect<true>;
    'app-users': AppUsersSelect<false> | AppUsersSelect<true>;
    babies: BabiesSelect<false> | BabiesSelect<true>;
    'baby-users': BabyUsersSelect<false> | BabyUsersSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'daily-stats': DailyStatsSelect<false> | DailyStatsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: CmsAdmin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface CmsAdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-admins".
 */
export interface CmsAdmin {
  id: number;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'cms-admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-users".
 */
export interface AppUser {
  id: string;
  username: string;
  /**
   * 创建用户或重置密码时填写，留空则不修改。
   */
  passwordInput?: string | null;
  password?: string | null;
  name?: string | null;
  email?: string | null;
  image?: string | null;
  emailVerified?: string | null;
  role: 'ADMIN' | 'DAD' | 'MOM' | 'NANNY' | 'GRANDPARENT' | 'OTHER';
  createdAt?: string | null;
  updatedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "babies".
 */
export interface Baby {
  id: string;
  name: string;
  fullName?: string | null;
  avatarUrl?: string | null;
  birthDate?: string | null;
  gender: 'BOY' | 'GIRL' | 'OTHER';
  createdAt?: string | null;
  updatedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "baby-users".
 */
export interface BabyUser {
  id: string;
  baby: string | Baby;
  user: string | AppUser;
  isDefault?: boolean | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: string;
  type:
    | 'SLEEP'
    | 'DIAPER'
    | 'BREASTFEED'
    | 'BOTTLE'
    | 'PUMP'
    | 'HEAD_LIFT'
    | 'PASSIVE_EXERCISE'
    | 'ROLL_OVER'
    | 'PULL_TO_SIT'
    | 'GAS_EXERCISE'
    | 'BATH'
    | 'OUTDOOR'
    | 'EARLY_EDUCATION'
    | 'SUPPLEMENT'
    | 'SPIT_UP';
  startTime: string;
  endTime?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
  babyId: string;
  hasPoop?: boolean | null;
  hasPee?: boolean | null;
  poopColor?: ('YELLOW' | 'GREEN' | 'BROWN' | 'BLACK' | 'WHITE' | 'RED') | null;
  poopPhotoUrl?: string | null;
  peeAmount?: ('SMALL' | 'MEDIUM' | 'LARGE') | null;
  burpSuccess?: boolean | null;
  milkAmount?: number | null;
  milkSource?: ('BREAST_MILK' | 'FORMULA') | null;
  breastFirmness?: ('SOFT' | 'ELASTIC' | 'HARD') | null;
  supplementType?: ('AD' | 'D3') | null;
  spitUpType?: ('NORMAL' | 'PROJECTILE') | null;
  count?: number | null;
  notes?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-stats".
 */
export interface DailyStat {
  id: string;
  date: string;
  babyId: string;
  sleepCount: number;
  totalSleepMinutes: number;
  breastfeedCount: number;
  totalBreastfeedMinutes: number;
  bottleCount: number;
  totalMilkAmount: number;
  pumpCount: number;
  totalPumpMilkAmount: number;
  diaperCount: number;
  poopCount: number;
  peeCount: number;
  exerciseCount: number;
  totalHeadLiftMinutes: number;
  supplementADCount: number;
  supplementD3Count: number;
  spitUpCount: number;
  projectileSpitUpCount: number;
  createdAt?: string | null;
  updatedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  action: 'CREATE' | 'UPDATE' | 'DELETE';
  resourceType: 'ACTIVITY';
  resourceId?: string | null;
  inputMethod: 'TEXT' | 'VOICE';
  inputText?: string | null;
  description?: string | null;
  success: boolean;
  errorMessage?: string | null;
  beforeData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  afterData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  babyId?: string | null;
  activityId?: string | null;
  userId?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'cms-admins';
        value: number | CmsAdmin;
      } | null)
    | ({
        relationTo: 'app-users';
        value: string | AppUser;
      } | null)
    | ({
        relationTo: 'babies';
        value: string | Baby;
      } | null)
    | ({
        relationTo: 'baby-users';
        value: string | BabyUser;
      } | null)
    | ({
        relationTo: 'activities';
        value: string | Activity;
      } | null)
    | ({
        relationTo: 'daily-stats';
        value: string | DailyStat;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'cms-admins';
    value: number | CmsAdmin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'cms-admins';
    value: number | CmsAdmin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cms-admins_select".
 */
export interface CmsAdminsSelect<T extends boolean = true> {
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-users_select".
 */
export interface AppUsersSelect<T extends boolean = true> {
  id?: T;
  username?: T;
  passwordInput?: T;
  password?: T;
  name?: T;
  email?: T;
  image?: T;
  emailVerified?: T;
  role?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "babies_select".
 */
export interface BabiesSelect<T extends boolean = true> {
  id?: T;
  name?: T;
  fullName?: T;
  avatarUrl?: T;
  birthDate?: T;
  gender?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "baby-users_select".
 */
export interface BabyUsersSelect<T extends boolean = true> {
  id?: T;
  baby?: T;
  user?: T;
  isDefault?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  id?: T;
  type?: T;
  startTime?: T;
  endTime?: T;
  createdAt?: T;
  updatedAt?: T;
  babyId?: T;
  hasPoop?: T;
  hasPee?: T;
  poopColor?: T;
  poopPhotoUrl?: T;
  peeAmount?: T;
  burpSuccess?: T;
  milkAmount?: T;
  milkSource?: T;
  breastFirmness?: T;
  supplementType?: T;
  spitUpType?: T;
  count?: T;
  notes?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-stats_select".
 */
export interface DailyStatsSelect<T extends boolean = true> {
  id?: T;
  date?: T;
  babyId?: T;
  sleepCount?: T;
  totalSleepMinutes?: T;
  breastfeedCount?: T;
  totalBreastfeedMinutes?: T;
  bottleCount?: T;
  totalMilkAmount?: T;
  pumpCount?: T;
  totalPumpMilkAmount?: T;
  diaperCount?: T;
  poopCount?: T;
  peeCount?: T;
  exerciseCount?: T;
  totalHeadLiftMinutes?: T;
  supplementADCount?: T;
  supplementD3Count?: T;
  spitUpCount?: T;
  projectileSpitUpCount?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  id?: T;
  action?: T;
  resourceType?: T;
  resourceId?: T;
  inputMethod?: T;
  inputText?: T;
  description?: T;
  success?: T;
  errorMessage?: T;
  beforeData?: T;
  afterData?: T;
  babyId?: T;
  activityId?: T;
  userId?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}