/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get activity list */
        get: operations["getActivities"];
        /**
         * Batch update activity dates
         * @description Move selected activities to a different date while preserving time of day
         */
        put: operations["batchUpdateActivityDate"];
        /** Create new activity */
        post: operations["createActivity"];
        /** Batch delete activities */
        delete: operations["batchDeleteActivities"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest activity by types */
        get: operations["getLatestActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get single activity */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        /** Delete activity */
        delete: operations["deleteActivity"];
        options?: never;
        head?: never;
        /** Update activity */
        patch: operations["updateActivity"];
        trace?: never;
    };
    "/activities/upload-photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload activity photo */
        post: operations["uploadActivityPhoto"];
        /** Delete activity photo */
        delete: operations["deleteActivityPhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voice-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse voice input and create activity
         * @description Accepts natural language text (from voice input) and uses AI to parse it into a structured activity record.
         *     Supports Chinese input like "宝宝喝了80毫升奶" or "刚换了尿布，有便便".
         */
        post: operations["parseVoiceInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get audit logs */
        get: operations["getAudits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/baby-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get baby profile */
        get: operations["getBabyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update baby profile */
        patch: operations["updateBabyProfile"];
        trace?: never;
    };
    "/baby-profile/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload baby avatar */
        post: operations["uploadAvatar"];
        /** Delete baby avatar */
        delete: operations["deleteAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get daily statistics list
         * @description Get daily statistics within a date range
         */
        get: operations["getDailyStats"];
        put?: never;
        /**
         * Compute and store daily statistics
         * @description Compute statistics for a specific date and store in database
         */
        post: operations["computeDailyStat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/daily-stats/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get daily statistics for a specific date */
        get: operations["getDailyStat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ActivityType: "SLEEP" | "DIAPER" | "BREASTFEED" | "BOTTLE" | "PUMP" | "HEAD_LIFT" | "PASSIVE_EXERCISE" | "ROLL_OVER" | "PULL_TO_SIT" | "GAS_EXERCISE" | "BATH" | "OUTDOOR" | "EARLY_EDUCATION" | "SUPPLEMENT" | "SPIT_UP";
        /** @enum {string} */
        MilkSource: "BREAST_MILK" | "FORMULA";
        /** @enum {string} */
        PoopColor: "YELLOW" | "GREEN" | "BROWN" | "BLACK" | "WHITE" | "RED";
        /** @enum {string} */
        PeeAmount: "SMALL" | "MEDIUM" | "LARGE";
        /** @enum {string} */
        BreastFirmness: "SOFT" | "ELASTIC" | "HARD";
        /** @enum {string} */
        SupplementType: "AD" | "D3" | "PROBIOTICS" | "PREBIOTICS";
        /** @enum {string} */
        SpitUpType: "NORMAL" | "PROJECTILE";
        /** @enum {string} */
        InputMethod: "TEXT" | "VOICE";
        /** @enum {string} */
        AuditAction: "CREATE" | "UPDATE" | "DELETE";
        /** @enum {string} */
        ResourceType: "ACTIVITY";
        AuditLog: {
            id: string;
            action: components["schemas"]["AuditAction"];
            resourceType: components["schemas"]["ResourceType"];
            /** @description 资源ID */
            resourceId?: string | null;
            inputMethod: components["schemas"]["InputMethod"];
            /** @description 原始输入内容（语音输入） */
            inputText?: string | null;
            /** @description 简短描述 */
            description?: string | null;
            /** @description 是否成功 */
            success: boolean;
            /** @description 错误信息 */
            errorMessage?: string | null;
            /** @description 修改前的资源内容 */
            beforeData?: Record<string, never> | null;
            /** @description 修改后的资源内容 */
            afterData?: Record<string, never> | null;
            /** @description 关联的活动ID */
            activityId?: string | null;
            /**
             * Format: date-time
             * @description 操作时间
             */
            createdAt: string;
        };
        Activity: {
            id: string;
            type: components["schemas"]["ActivityType"];
            /**
             * Format: date-time
             * @description 活动开始时间
             */
            startTime: string;
            /**
             * Format: date-time
             * @description 活动结束时间（正在进行的活动没有结束时间）
             */
            endTime?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            hasPoop?: boolean | null;
            hasPee?: boolean | null;
            poopColor?: components["schemas"]["PoopColor"];
            poopPhotoUrl?: string | null;
            peeAmount?: components["schemas"]["PeeAmount"];
            burpSuccess?: boolean | null;
            milkAmount?: number | null;
            milkSource?: components["schemas"]["MilkSource"];
            breastFirmness?: components["schemas"]["BreastFirmness"];
            supplementType?: components["schemas"]["SupplementType"];
            spitUpType?: components["schemas"]["SpitUpType"];
            /** @description 次数（用于翻身、拉坐等计数类活动） */
            count?: number | null;
            notes?: string | null;
        };
        CreateActivityInput: {
            type: components["schemas"]["ActivityType"];
            /**
             * Format: date-time
             * @description 活动开始时间
             */
            startTime: string;
            /**
             * Format: date-time
             * @description 活动结束时间（可选）
             */
            endTime?: string;
            hasPoop?: boolean;
            hasPee?: boolean;
            poopColor?: components["schemas"]["PoopColor"];
            poopPhotoUrl?: string;
            peeAmount?: components["schemas"]["PeeAmount"];
            burpSuccess?: boolean;
            milkAmount?: number;
            milkSource?: components["schemas"]["MilkSource"];
            breastFirmness?: components["schemas"]["BreastFirmness"];
            supplementType?: components["schemas"]["SupplementType"];
            spitUpType?: components["schemas"]["SpitUpType"];
            /** @description 次数（用于翻身、拉坐等计数类活动） */
            count?: number;
            notes?: string;
            /** @description Force create even if there's an overlap warning (not for duplicates) */
            force?: boolean;
        };
        UpdateActivityInput: {
            type?: components["schemas"]["ActivityType"];
            /**
             * Format: date-time
             * @description 活动开始时间
             */
            startTime?: string;
            /**
             * Format: date-time
             * @description 活动结束时间
             */
            endTime?: string;
            hasPoop?: boolean;
            hasPee?: boolean;
            poopColor?: components["schemas"]["PoopColor"];
            poopPhotoUrl?: string;
            peeAmount?: components["schemas"]["PeeAmount"];
            burpSuccess?: boolean;
            milkAmount?: number;
            milkSource?: components["schemas"]["MilkSource"];
            breastFirmness?: components["schemas"]["BreastFirmness"];
            supplementType?: components["schemas"]["SupplementType"];
            spitUpType?: components["schemas"]["SpitUpType"];
            /** @description 次数（用于翻身、拉坐等计数类活动） */
            count?: number;
            notes?: string;
        };
        BabyProfile: {
            id: string;
            name?: string | null;
            avatarUrl?: string | null;
            /** Format: date-time */
            birthDate?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateBabyProfileInput: {
            name?: string;
            avatarUrl?: string;
            /** Format: date-time */
            birthDate?: string;
        };
        Error: {
            error: string;
        };
        ActivityConflictError: {
            /** @description Human-readable error message */
            error: string;
            /**
             * @description DUPLICATE_ACTIVITY - Same type activity exists at same time (cannot be overridden)
             *     OVERLAP_ACTIVITY - Time overlaps with another activity (can be overridden with force=true)
             * @enum {string}
             */
            code: "DUPLICATE_ACTIVITY" | "OVERLAP_ACTIVITY";
            conflictingActivity?: components["schemas"]["Activity"];
        };
        DailyStat: {
            id: string;
            /**
             * Format: date-time
             * @description 统计日期
             */
            date: string;
            /** @description 睡眠次数 */
            sleepCount?: number;
            /** @description 总睡眠时长（分钟） */
            totalSleepMinutes?: number;
            /** @description 亲喂次数 */
            breastfeedCount?: number;
            /** @description 亲喂总时长（分钟） */
            totalBreastfeedMinutes?: number;
            /** @description 瓶喂次数 */
            bottleCount?: number;
            /** @description 瓶喂总奶量（毫升） */
            totalMilkAmount?: number;
            /** @description 吸奶次数 */
            pumpCount?: number;
            /** @description 吸奶总奶量（毫升） */
            totalPumpMilkAmount?: number;
            /** @description 换尿布次数 */
            diaperCount?: number;
            /** @description 大便次数 */
            poopCount?: number;
            /** @description 小便次数 */
            peeCount?: number;
            /** @description 活动次数 */
            exerciseCount?: number;
            /** @description 抬头总时长（分钟） */
            totalHeadLiftMinutes?: number;
            /** @description AD补剂次数 */
            supplementADCount?: number;
            /** @description D3补剂次数 */
            supplementD3Count?: number;
            /** @description 益生菌次数 */
            supplementProbioticsCount?: number;
            /** @description 益生元次数 */
            supplementPrebioticsCount?: number;
            /** @description 吐奶次数 */
            spitUpCount?: number;
            /** @description 喷射性吐奶次数 */
            projectileSpitUpCount?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: {
        /** @description Server error */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getActivities: {
        parameters: {
            query?: {
                limit?: number;
                type?: components["schemas"]["ActivityType"];
                /** @description Comma-separated list of activity types to filter */
                types?: string;
                /** @description Date in YYYY-MM-DD format (returns activities for this day including cross-midnight) */
                date?: string;
                /** @description Filter activities with startTime >= this value (ISO format) */
                startTimeGte?: string;
                /** @description Filter activities with startTime < this value (ISO format) */
                startTimeLt?: string;
                /** @description When true, also include activities that started before startTimeGte but have endTime >= startTimeGte */
                crossStartTime?: boolean;
                /** @description When true, also include activities that started before startTimeLt but have endTime >= startTimeLt (i.e., activities that extend past the end boundary) */
                crossEndTime?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    batchUpdateActivityDate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Activity IDs to update */
                    ids: string[];
                    /**
                     * Format: date
                     * @description Target date (YYYY-MM-DD format) to move activities to
                     */
                    targetDate: string;
                };
            };
        };
        responses: {
            /** @description Update success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        count?: number;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    createActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivityInput"];
            };
        };
        responses: {
            /** @description Created activity */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Time conflict with existing activity */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityConflictError"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    batchDeleteActivities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ids: string[];
                };
            };
        };
        responses: {
            /** @description Deletion success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        count?: number;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getLatestActivity: {
        parameters: {
            query: {
                /** @description Comma-separated list of activity types */
                types: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest activity (null if not found) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"] | null;
                };
            };
            /** @description Bad request - types parameter required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            /** @description Activity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    deleteActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    updateActivity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActivityInput"];
            };
        };
        responses: {
            /** @description Updated activity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    uploadActivityPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    category?: string;
                };
            };
        };
        responses: {
            /** @description Upload success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url?: string;
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    deleteActivityPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    url: string;
                };
            };
        };
        responses: {
            /** @description Deletion success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    parseVoiceInput: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description The voice input text to parse
                     * @example 宝宝刚才喝了60毫升奶
                     */
                    text: string;
                };
            };
        };
        responses: {
            /** @description Activity created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        activity?: components["schemas"]["Activity"];
                        parsed?: {
                            /** @description AI confidence level (0-1) */
                            confidence?: number;
                            originalText?: string;
                        };
                        /** @description Human-readable confirmation message */
                        message?: string;
                    };
                };
            };
            /** @description Parse failed or invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                        /** @enum {string} */
                        code?: "MISSING_TEXT" | "PARSE_FAILED" | "INVALID_TYPE";
                        originalText?: string;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getAudits: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Filter by action type */
                action?: components["schemas"]["AuditAction"];
                /** @description Filter by resource type */
                resourceType?: components["schemas"]["ResourceType"];
                /** @description Filter by success status */
                success?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit log list with pagination info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["AuditLog"][];
                        total?: number;
                        hasMore?: boolean;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getBabyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Baby profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BabyProfile"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    updateBabyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBabyProfileInput"];
            };
        };
        responses: {
            /** @description Updated baby profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BabyProfile"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Upload success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        url?: string;
                        profile?: components["schemas"]["BabyProfile"];
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    deleteAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getDailyStats: {
        parameters: {
            query?: {
                /** @description Start date (YYYY-MM-DD format) */
                startDate?: string;
                /** @description End date (YYYY-MM-DD format) */
                endDate?: string;
                /** @description Maximum number of records to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily statistics list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyStat"][];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    computeDailyStat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: date
                     * @description Date to compute statistics for (YYYY-MM-DD format)
                     */
                    date: string;
                };
            };
        };
        responses: {
            /** @description Computed daily statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyStat"];
                };
            };
            /** @description Bad request - date is required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
    getDailyStat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Date in YYYY-MM-DD format */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daily statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyStat"];
                };
            };
            /** @description Invalid date format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Statistics not found for this date */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["ServerError"];
        };
    };
}
