name: Delete Neon Branch on PR Close

on:
  pull_request:
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  delete_neon_branch:
    name: Delete Neon Branch
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - appId: bubu-log
            projectId: morning-mouse-25532220
          - appId: nunu-island
            projectId: shy-feather-65398796
          - appId: nunu-log
            projectId: shiny-dream-05784525
          - appId: wedding-invite
            projectId: small-wind-49890586
    steps:
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3
        continue-on-error: true
        with:
          project_id: ${{ matrix.projectId }}
          branch: preview/${{ github.event.pull_request.head.ref }}
          api_key: ${{ secrets.NEON_API_KEY }}
